### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'click')

### ISSUE THREAD

**Issue by alexdibella** [robinnorth/google-migration-utils#3]
Hi, thanks for updating the script! I tried to run it and get the following error (removed absolute path info):

`Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'click')
    at pptr://__puppeteer_evaluation_script__:6:53
    at ExecutionContext._ExecutionContext_evaluate (google-migration-utils/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (google-migration-utils/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async Object.importPlaces [as handler] (file:///google-migration-utils/src/maps/importPlaces.js:115:24)`

I have never used JS, so not sure what's happening? Any guidance would be great thanks! Let me know if more info are necessary :)

**Comment by AlexanderErdl** [comment]
I am getting the same error :( Would be grateful for any guidance also! :)

**Comment by sourencho** [comment]
I am also getting this error

**Comment by PaulRBerg** [comment]
I have just bumped into the same issue.

@kitschpatrol what exactly did you do to "bypass the automated login and skip directly to the user-interactive login strategy"?

**Comment by PaulRBerg** [comment]
Also, I think I know on which specific line this bug occurs. It's line 109:

https://github.com/robinnorth/google-migration-utils/blob/b9965eb4ef817f53c0fc58190d530724f353c06d/src/maps/importPlaces.js#L109

And the reason is that the id of the "Next" button has changed.

**Comment by robinnorth** [comment]
Fixed in #7, thanks @PaulRBerg 🙏
